author: Luciano Brum
title: Tek Broon
email: lucianobrum18@gmail.com
baseurl: ""
url: "https://lubrum.github.io/"
linkedin_username: Luciano Brum
linkedin_link: luciano-moraes-da-luz-brum-12532a77
github_username:  Lubrum
youtube_username: Luciano Brum
youtube_link: channel/UCAX8r-2riNaYslvOQjgM5PQ
instagram_username: lucianobrum18

google_analytics: UA-179504871-1
    
permalink: /:title
plugins:
  - jekyll-feed

exclude: []
include: ["node_modules"]

languages:
  - pt
  - en